### ISSUE TITLE
Update the algorithms to no longer use databases

### ISSUE THREAD

**Issue by EdrianI** [openeew/openeew-seismology#13]

**Comment by johnwalicki** [comment]
Do we want to define a MQTT topic that the detection algorithm would publish when it detects an earthquake event?  What earthquake details would be stored in this database?  We could have a secondary process subscribe to those events and it would know how to write to a Cloudant DB.

Would be easy to create a Node-RED flow to do the backend part of that.

**Comment by vkuna** [comment]
John, yes, I think the algorithm will publish two topics, detections and earthquakes. I am now starting to work on it so I will think about how to make the event more lightweight and what essential info in will store.

**Comment by johnwalicki** [comment]
What parameter attributes would the detection algorithm emit?
Time, devices, magnitude, etc?
We could start to define a JSON object that gets passed as part of the MQTT published event.

**Comment by vkuna** [comment]
Yes, for the earthquake topic it would be time, location, magnitude, detections it contains.. But it is more complicated because all these parameters update every second as we get more data.. So there would be a point where we say, 'alright, this is surely an earthquake, lets publish it to MQTT'. But then we want to update that info each sec and refine the event as we go.. So we need to think about how that would work

**Comment by andygrillo** [comment]
That is the benefit of mqtt in that we can keep sending new msgs as the eq
develops.

I guess we should id every earthquake event so we can associate detections
to specific ids in each json

**Comment by EdrianI** [comment]
The output of the algorithms should be tracked in another GitHub issue.

**Comment by johnwalicki** [comment]
Agreed - Let's focus this issue on the rewrite to remove the database, MQTT topic discussion will move to https://github.com/openeew/openeew-seismology/issues/16
